/**
 * Compact share-hash codec — pure, open, no UI deps.
 *
 * Format: `v1.<base64url(bytes)>` (single blob; optional tails omitted when default).
 *
 * ## Docs (read these before changing the wire format)
 *
 * - **Wire spec (bytes, flags, catalogs):** `docs/SHARE_HASH.md`
 * - **Vendoring / “Open in Heatmap” for other tools:** `docs/SHARE_HASH_VENDORING.md`
 *   Prefer Mode A (`encodeRawPlanHash`) for external calculators; Mode B builders are stretch.
 *
 * Catalogs: `src/data/itemIds.json`, `recipeIds.json`, `recipePrimaries.json`
 * (synced from `public/data/recipes/` by `npm run parse-docs`; append-only).
 *
 * Design choices (vs pipe-delimited sections / hex / name tokens):
 * - One binary payload is denser than `seed|plan|config` pipes; flags already drop
 *   default seed / extractors / empty lists.
 * - base64url (~6 bits/char) beats hex (4) and matches Base62 for practical lengths.
 * - Item/recipe **indices** into append-only catalogs — not ClassName strings.
 */
import itemIdsJson from "@/data/itemIds.json";
import recipeIdsJson from "@/data/recipeIds.json";
import recipePrimariesJson from "@/data/recipePrimaries.json";
import { clampClockPercent } from "@/lib/mining";
import { canonicalizeProductId } from "@/lib/productIdAliases";
import { RAW_RESOURCE_OPTIONS } from "@/lib/resources";
import type { MapSeed } from "@/lib/seed";
import type {
  InputMode,
  MinerMk,
  MinerSettings,
  ProductTargetLine,
  RawDemandLine,
  ScoringMode,
  ScoringOptions,
} from "@/types";
import { DEFAULT_MINER_SETTINGS, DEFAULT_SCORING_OPTIONS } from "@/types";

/** Public wire version. Breaking changes increment this. */
export const PLAN_HASH_VERSION = 1 as const;

/** flags bit 2: haul is plan-view only (includeElevation = false) */
const FLAG_FLAT_HAUL = 1 << 2;
/** flags bit 5: world seed present after demand payload */
const FLAG_HAS_SEED = 1 << 5;
/** flags bit 6: external item list after optional seed */
const FLAG_HAS_EXTERNAL = 1 << 6;
/**
 * flags bit 7: trailing extractor extension present
 * Layout: waterClock u8, wellClock u8, wellFlags u8 (bit0 = wells enabled), oilClock u8.
 * Omitted when all extractor fields match {@link DEFAULT_MINER_SETTINGS}.
 */
const FLAG_HAS_EXTRACTOR_EXT = 1 << 7;

const RAW_IDS: readonly string[] = RAW_RESOURCE_OPTIONS;
const MAX_LINES = 15;
const MAX_RATE = 65_535;
const MAX_EXTERNAL = 15;
const MAX_RECIPE_OVERRIDES = 20;

/** Append-only ClassName → index tables (committed; regenerated by parse-docs). */
export const ITEM_IDS: readonly string[] = itemIdsJson as string[];
export const RECIPE_IDS: readonly string[] = recipeIdsJson as string[];

/** recipe ClassName → primary product ClassName (Docs first product line). */
const RECIPE_PRIMARY = recipePrimariesJson as Record<string, string>;

const itemIndexById = new Map<string, number>(ITEM_IDS.map((id, i) => [id, i]));
const recipeIndexById = new Map<string, number>(RECIPE_IDS.map((id, i) => [id, i]));

if (ITEM_IDS.length > 256) {
  throw new Error(`itemIds catalog has ${ITEM_IDS.length} entries; wire format uses u8 indices`);
}
if (RECIPE_IDS.length > 65_535) {
  throw new Error(
    `recipeIds catalog has ${RECIPE_IDS.length} entries; wire format uses u16 indices`,
  );
}

/** Fields applied from a shared link (scoring display knobs stay local). */
export type PlanSnapshot = {
  mode: InputMode;
  rawDemand: Array<{ resource: string; itemsPerMinute: number }>;
  productTargets: Array<{ productId: string; itemsPerMinute: number }>;
  miner: MinerSettings;
  scoringMode: ScoringMode;
  /** Computation knobs from the hash (display knobs stay local). */
  scoringOptions: Pick<
    ScoringOptions,
    "centerPower" | "topN" | "siteSepFraction" | "includeElevation"
  >;
  /** null = Default / vanilla layout; number (incl. 0) = randomized map seed. */
  seed: MapSeed;
  /**
   * Mode B: crafted item ids treated as off-site (not expanded into map raws).
   * Empty when absent.
   */
  externalItems: string[];
  /**
   * Mode B: product itemId → recipe ClassName (non-default picks only).
   * Empty when absent.
   */
  recipeOverrides: Record<string, string>;
};

export type PlanHashSource = {
  mode: InputMode;
  rawDemand: RawDemandLine[];
  productTargets: ProductTargetLine[];
  miner: MinerSettings;
  scoringMode: ScoringMode;
  scoringOptions: ScoringOptions;
  seed: MapSeed;
  /** Mode B off-site intermediates (optional; omitted from hash when empty). */
  externalItems?: string[];
  /** Mode B alternate recipe picks (optional; omitted when empty). */
  recipeOverrides?: Record<string, string>;
};

function clamp(n: number, lo: number, hi: number, fallback: number): number {
  if (!Number.isFinite(n)) return fallback;
  return Math.min(hi, Math.max(lo, n));
}

/** Normalize miner/extractor settings with defaults for older snapshots. */
export function normalizeMinerSettings(partial: Partial<MinerSettings> | undefined): MinerSettings {
  const m = partial ?? {};
  const minerMk = (
    [1, 2, 3].includes(m.minerMk as number) ? m.minerMk : DEFAULT_MINER_SETTINGS.minerMk
  ) as MinerMk;
  return {
    minerMk,
    clockPercent: clampClockPercent(m.clockPercent as number, DEFAULT_MINER_SETTINGS.clockPercent),
    oilClockPercent: clampClockPercent(
      m.oilClockPercent as number,
      DEFAULT_MINER_SETTINGS.oilClockPercent,
    ),
    waterClockPercent: clampClockPercent(
      m.waterClockPercent as number,
      DEFAULT_MINER_SETTINGS.waterClockPercent,
    ),
    resourceWellsEnabled:
      typeof m.resourceWellsEnabled === "boolean"
        ? m.resourceWellsEnabled
        : DEFAULT_MINER_SETTINGS.resourceWellsEnabled,
    wellClockPercent: clampClockPercent(
      m.wellClockPercent as number,
      DEFAULT_MINER_SETTINGS.wellClockPercent,
    ),
  };
}

function quantize(value: number, min: number, step: number, maxSteps: number): number {
  const q = Math.round((value - min) / step);
  return Math.min(maxSteps, Math.max(0, q));
}

function dequantize(q: number, min: number, step: number): number {
  return min + q * step;
}

function normalizeExternalItems(ids: string[] | undefined): string[] {
  if (!ids || ids.length === 0) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of ids) {
    if (!raw) continue;
    const id = canonicalizeProductId(raw);
    if (seen.has(id)) continue;
    if (itemIndexById.get(id) === undefined) continue;
    seen.add(id);
    out.push(id);
    if (out.length >= MAX_EXTERNAL) break;
  }
  out.sort((a, b) => a.localeCompare(b));
  return out;
}

/**
 * Normalize recipe overrides: product itemId → recipe ClassName.
 * Sorted by product id for stable hashes; capped at {@link MAX_RECIPE_OVERRIDES}.
 * Drops pairs missing from the share-hash catalogs.
 */
export function normalizeRecipeOverrides(
  overrides: Record<string, string> | undefined | null,
): Record<string, string> {
  if (!overrides) return {};
  const entries: Array<[string, string]> = [];
  for (const [rawProduct, rawRecipe] of Object.entries(overrides)) {
    if (!rawProduct || !rawRecipe) continue;
    const productId = canonicalizeProductId(rawProduct);
    const recipeId = rawRecipe.trim();
    if (!productId || !recipeId) continue;
    if (itemIndexById.get(productId) === undefined) continue;
    if (recipeIndexById.get(recipeId) === undefined) continue;
    entries.push([productId, recipeId]);
  }
  entries.sort((a, b) => a[0].localeCompare(b[0]));
  const out: Record<string, string> = {};
  for (const [p, r] of entries.slice(0, MAX_RECIPE_OVERRIDES)) {
    out[p] = r;
  }
  return out;
}

export function toSnapshot(source: PlanHashSource): PlanSnapshot {
  const seed: MapSeed =
    source.seed === null || source.seed === undefined ? null : Number(source.seed) | 0;
  return {
    mode: source.mode === "product" ? "product" : "raw",
    rawDemand: source.rawDemand
      .filter((l) => l.resource)
      .slice(0, MAX_LINES)
      .map((l) => ({
        resource: l.resource,
        itemsPerMinute: Math.min(MAX_RATE, Math.max(0, Math.round(Number(l.itemsPerMinute) || 0))),
      })),
    productTargets: source.productTargets
      .filter((l) => l.productId)
      .slice(0, MAX_LINES)
      .map((l) => ({
        productId: canonicalizeProductId(l.productId),
        itemsPerMinute: Math.min(MAX_RATE, Math.max(0, Math.round(Number(l.itemsPerMinute) || 0))),
      })),
    miner: normalizeMinerSettings(source.miner),
    scoringMode: source.scoringMode === "weighted" ? "weighted" : "centered",
    scoringOptions: {
      centerPower: clamp(
        source.scoringOptions.centerPower,
        1,
        2.5,
        DEFAULT_SCORING_OPTIONS.centerPower,
      ),
      topN: Math.round(clamp(source.scoringOptions.topN, 3, 10, DEFAULT_SCORING_OPTIONS.topN)),
      siteSepFraction: clamp(
        source.scoringOptions.siteSepFraction,
        0.04,
        0.4,
        DEFAULT_SCORING_OPTIONS.siteSepFraction,
      ),
      includeElevation: source.scoringOptions.includeElevation !== false,
    },
    seed,
    externalItems: normalizeExternalItems(source.externalItems),
    recipeOverrides: normalizeRecipeOverrides(source.recipeOverrides),
  };
}

function indexOfRaw(id: string): number {
  return RAW_IDS.indexOf(id);
}

function indexOfItem(id: string): number {
  return itemIndexById.get(canonicalizeProductId(id)) ?? -1;
}

function itemAt(index: number): string | undefined {
  return ITEM_IDS[index];
}

function indexOfRecipe(id: string): number {
  return recipeIndexById.get(id.trim()) ?? -1;
}

function recipeAt(index: number): string | undefined {
  return RECIPE_IDS[index];
}

function extractorIsDefault(m: MinerSettings): boolean {
  return (
    m.waterClockPercent === DEFAULT_MINER_SETTINGS.waterClockPercent &&
    m.wellClockPercent === DEFAULT_MINER_SETTINGS.wellClockPercent &&
    m.resourceWellsEnabled === DEFAULT_MINER_SETTINGS.resourceWellsEnabled &&
    m.oilClockPercent === DEFAULT_MINER_SETTINGS.oilClockPercent
  );
}

type EncodedProduct = { itemIndex: number; rate: number };
type EncodedOverride = { itemIndex: number; recipeIndex: number };

function productsToEncode(products: PlanSnapshot["productTargets"]): EncodedProduct[] {
  const out: EncodedProduct[] = [];
  for (const d of products) {
    if (!d.productId) continue;
    const itemIndex = indexOfItem(d.productId);
    if (itemIndex < 0) continue;
    out.push({
      itemIndex,
      rate: Math.min(MAX_RATE, Math.max(0, Math.round(d.itemsPerMinute))),
    });
    if (out.length >= MAX_LINES) break;
  }
  return out;
}

function externalToEncode(ids: string[]): number[] {
  const out: number[] = [];
  for (const id of normalizeExternalItems(ids)) {
    const idx = indexOfItem(id);
    if (idx < 0) continue;
    out.push(idx);
    if (out.length >= MAX_EXTERNAL) break;
  }
  return out;
}

function recipeOverridesToEncode(overrides: Record<string, string> | undefined): EncodedOverride[] {
  const norm = normalizeRecipeOverrides(overrides);
  const out: EncodedOverride[] = [];
  for (const [productId, recipeId] of Object.entries(norm)) {
    const itemIndex = indexOfItem(productId);
    const recipeIndex = indexOfRecipe(recipeId);
    if (itemIndex < 0 || recipeIndex < 0) continue;
    out.push({ itemIndex, recipeIndex });
    if (out.length >= MAX_RECIPE_OVERRIDES) break;
  }
  return out;
}

export function encodePlanBytes(snap: PlanSnapshot): Uint8Array {
  const raw = snap.rawDemand.filter((d) => indexOfRaw(d.resource) >= 0).slice(0, MAX_LINES);
  const activeRaw = snap.mode === "raw" ? raw : [];
  const activeProducts = snap.mode === "product" ? productsToEncode(snap.productTargets) : [];
  const activeExternal = snap.mode === "product" ? externalToEncode(snap.externalItems ?? []) : [];
  const activeOverrides =
    snap.mode === "product" ? recipeOverridesToEncode(snap.recipeOverrides) : [];

  const out: number[] = [];

  const mkBits = Math.min(2, Math.max(0, snap.miner.minerMk - 1));
  let flags = 0;
  if (snap.mode === "product") flags |= 1;
  if (snap.scoringMode === "weighted") flags |= 2;
  if (snap.scoringOptions.includeElevation === false) flags |= FLAG_FLAT_HAUL;
  flags |= (mkBits & 3) << 3;
  const hasSeed = snap.seed !== null && snap.seed !== undefined;
  if (hasSeed) flags |= FLAG_HAS_SEED;
  const hasExternal = activeExternal.length > 0;
  if (hasExternal) flags |= FLAG_HAS_EXTERNAL;
  const hasExtractorExt = !extractorIsDefault(snap.miner);
  if (hasExtractorExt) flags |= FLAG_HAS_EXTRACTOR_EXT;
  out.push(flags);

  out.push(clampClockPercent(snap.miner.clockPercent, DEFAULT_MINER_SETTINGS.clockPercent));

  // Computation knobs (2 bytes): centerPower 5 | topN 3 | siteSep 5
  const cp = quantize(snap.scoringOptions.centerPower, 1, 0.05, 30);
  const tn = Math.min(7, Math.max(0, snap.scoringOptions.topN - 3));
  const ss = quantize(snap.scoringOptions.siteSepFraction, 0.04, 0.02, 18);
  const packed = (cp & 31) | ((tn & 7) << 5) | ((ss & 31) << 8);
  out.push(packed & 0xff);
  out.push((packed >>> 8) & 0xff);

  out.push((activeRaw.length & 15) | ((activeProducts.length & 15) << 4));

  for (const d of activeRaw) {
    out.push(indexOfRaw(d.resource) & 0xff);
    const rate = Math.min(MAX_RATE, Math.max(0, Math.round(d.itemsPerMinute)));
    out.push(rate & 0xff);
    out.push((rate >>> 8) & 0xff);
  }
  for (const d of activeProducts) {
    out.push(d.itemIndex & 0xff);
    out.push(d.rate & 0xff);
    out.push((d.rate >>> 8) & 0xff);
  }

  if (hasSeed && snap.seed !== null) {
    const s = snap.seed | 0;
    out.push(s & 0xff);
    out.push((s >>> 8) & 0xff);
    out.push((s >>> 16) & 0xff);
    out.push((s >>> 24) & 0xff);
  }

  if (hasExternal) {
    out.push(activeExternal.length & 0xff);
    for (const idx of activeExternal) out.push(idx & 0xff);
  }

  if (hasExtractorExt) {
    out.push(
      clampClockPercent(snap.miner.waterClockPercent, DEFAULT_MINER_SETTINGS.waterClockPercent),
    );
    out.push(
      clampClockPercent(snap.miner.wellClockPercent, DEFAULT_MINER_SETTINGS.wellClockPercent),
    );
    out.push(snap.miner.resourceWellsEnabled ? 1 : 0);
    out.push(clampClockPercent(snap.miner.oilClockPercent, DEFAULT_MINER_SETTINGS.oilClockPercent));
  }

  if (activeOverrides.length > 0) {
    out.push(activeOverrides.length & 0xff);
    for (const o of activeOverrides) {
      out.push(o.itemIndex & 0xff);
      out.push(o.recipeIndex & 0xff);
      out.push((o.recipeIndex >>> 8) & 0xff);
    }
  }

  return new Uint8Array(out);
}

export function decodePlanBytes(bytes: Uint8Array): PlanSnapshot | null {
  if (bytes.length < 4) return null;
  let i = 0;
  const flags = bytes[i++] ?? 0;
  const mode: InputMode = flags & 1 ? "product" : "raw";
  const scoringMode: ScoringMode = flags & 2 ? "weighted" : "centered";
  const includeElevation = (flags & FLAG_FLAT_HAUL) === 0;
  const minerMk = (Math.min(2, (flags >>> 3) & 3) + 1) as MinerMk;
  const hasSeed = (flags & FLAG_HAS_SEED) !== 0;
  const clockPercent = clampClockPercent(bytes[i++] ?? 100, DEFAULT_MINER_SETTINGS.clockPercent);

  const b0 = bytes[i++] ?? 0;
  const b1 = bytes[i++] ?? 0;
  const packed = b0 | (b1 << 8);
  const centerPower = dequantize(packed & 31, 1, 0.05);
  const topN = 3 + ((packed >>> 5) & 7);
  const siteSepFraction = dequantize((packed >>> 8) & 31, 0.04, 0.02);

  const counts = bytes[i++] ?? 0;
  const nRaw = counts & 15;
  const nProd = (counts >>> 4) & 15;

  if (i + nRaw * 3 + nProd * 3 > bytes.length) return null;

  const rawDemand: PlanSnapshot["rawDemand"] = [];
  for (let k = 0; k < nRaw; k++) {
    const idx = bytes[i++] ?? 0;
    const lo = bytes[i++] ?? 0;
    const hi = bytes[i++] ?? 0;
    const resource = RAW_IDS[idx];
    if (!resource) continue;
    rawDemand.push({ resource, itemsPerMinute: lo | (hi << 8) });
  }

  const productTargets: PlanSnapshot["productTargets"] = [];
  for (let k = 0; k < nProd; k++) {
    const itemIndex = bytes[i++] ?? 0;
    const lo = bytes[i++] ?? 0;
    const hi = bytes[i++] ?? 0;
    const productId = itemAt(itemIndex);
    if (!productId) continue;
    productTargets.push({
      productId,
      itemsPerMinute: lo | (hi << 8),
    });
  }

  let seed: MapSeed = null;
  if (hasSeed) {
    if (i + 4 > bytes.length) return null;
    const b0s = bytes[i++] ?? 0;
    const b1s = bytes[i++] ?? 0;
    const b2s = bytes[i++] ?? 0;
    const b3s = bytes[i++] ?? 0;
    seed = b0s | (b1s << 8) | (b2s << 16) | (b3s << 24) | 0;
  }

  const hasExternal = (flags & FLAG_HAS_EXTERNAL) !== 0;
  const externalItems: string[] = [];
  if (hasExternal) {
    if (i >= bytes.length) return null;
    const nExt = bytes[i++] ?? 0;
    if (nExt > MAX_EXTERNAL) return null;
    if (i + nExt > bytes.length) return null;
    for (let k = 0; k < nExt; k++) {
      const id = itemAt(bytes[i++] ?? 0);
      if (id) externalItems.push(id);
    }
  }

  const hasExtractorExt = (flags & FLAG_HAS_EXTRACTOR_EXT) !== 0;
  let waterClockPercent = DEFAULT_MINER_SETTINGS.waterClockPercent;
  let wellClockPercent = DEFAULT_MINER_SETTINGS.wellClockPercent;
  let oilClockPercent = DEFAULT_MINER_SETTINGS.oilClockPercent;
  let resourceWellsEnabled = DEFAULT_MINER_SETTINGS.resourceWellsEnabled;
  if (hasExtractorExt) {
    if (i + 4 > bytes.length) return null;
    waterClockPercent = clampClockPercent(
      bytes[i++] ?? 250,
      DEFAULT_MINER_SETTINGS.waterClockPercent,
    );
    wellClockPercent = clampClockPercent(
      bytes[i++] ?? 250,
      DEFAULT_MINER_SETTINGS.wellClockPercent,
    );
    resourceWellsEnabled = ((bytes[i++] ?? 0) & 1) !== 0;
    oilClockPercent = clampClockPercent(bytes[i++] ?? 250, DEFAULT_MINER_SETTINGS.oilClockPercent);
  }

  const recipeOverrides: Record<string, string> = {};
  if (i < bytes.length) {
    const nOv = bytes[i++] ?? 0;
    if (nOv > MAX_RECIPE_OVERRIDES) return null;
    if (i + nOv * 3 > bytes.length) return null;
    for (let k = 0; k < nOv; k++) {
      const pIdx = bytes[i++] ?? 0;
      const rLo = bytes[i++] ?? 0;
      const rHi = bytes[i++] ?? 0;
      const productId = itemAt(pIdx);
      const recipeId = recipeAt(rLo | (rHi << 8));
      if (!productId || !recipeId) continue;
      recipeOverrides[productId] = recipeId;
    }
  }

  return toSnapshot({
    mode,
    rawDemand: rawDemand.map((d, j) => ({ id: `h${j}`, ...d })),
    productTargets: productTargets.map((d, j) => ({ id: `h${j}`, ...d })),
    miner: {
      minerMk,
      clockPercent,
      oilClockPercent,
      waterClockPercent,
      wellClockPercent,
      resourceWellsEnabled,
    },
    scoringMode,
    scoringOptions: {
      ...DEFAULT_SCORING_OPTIONS,
      centerPower,
      topN,
      siteSepFraction,
      includeElevation,
    },
    seed,
    externalItems,
    recipeOverrides,
  });
}

/** True when two map seeds refer to the same world (both Default or same number). */
export function mapSeedsEqual(a: MapSeed, b: MapSeed): boolean {
  if (a === null && b === null) return true;
  if (a === null || b === null) return false;
  return (a | 0) === (b | 0);
}

export function bytesToBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function base64UrlToBytes(b64url: string): Uint8Array | null {
  try {
    const padded = b64url.replace(/-/g, "+").replace(/_/g, "/");
    const pad = padded.length % 4 === 0 ? "" : "=".repeat(4 - (padded.length % 4));
    const binary = atob(padded + pad);
    const bytes = new Uint8Array(binary.length);
    for (let j = 0; j < binary.length; j++) bytes[j] = binary.charCodeAt(j);
    return bytes;
  } catch {
    return null;
  }
}

export function encodePlanHash(source: PlanHashSource): string {
  const snap = toSnapshot(source);
  return `v${PLAN_HASH_VERSION}.${bytesToBase64Url(encodePlanBytes(snap))}`;
}

export function decodePlanHash(hash: string): PlanSnapshot | null {
  let raw = hash.trim();
  if (raw.startsWith("#")) raw = raw.slice(1);
  if (!raw) return null;

  const m = /^v(\d+)\.([A-Za-z0-9_-]+)$/.exec(raw);
  if (!m) return null;
  const version = Number(m[1]);
  const payload = m[2];
  if (!payload || version !== PLAN_HASH_VERSION) return null;

  const bytes = base64UrlToBytes(payload);
  if (!bytes) return null;
  return decodePlanBytes(bytes);
}

export function planHashEquals(a: PlanHashSource, b: PlanHashSource): boolean {
  return encodePlanHash(a) === encodePlanHash(b);
}

// ── Friendly builders (interop / “Open in Heatmap”) ─────────────────────────

export type RawLinkLine = { resource: string; itemsPerMinute: number };
export type ProductLinkTarget = { item: string; itemsPerMinute: number };

/**
 * Mode A interop helper: raw demand lines → share hash (map defaults assumed).
 * Resource ids are Docs ClassNames (`Desc_OreIron_C`, …).
 */
export function encodeRawPlanHash(
  demand: RawLinkLine[],
  opts?: {
    seed?: MapSeed;
    miner?: Partial<MinerSettings>;
    scoringMode?: ScoringMode;
    scoringOptions?: Partial<ScoringOptions>;
  },
): string {
  return encodePlanHash({
    mode: "raw",
    rawDemand: demand.map((d, i) => ({
      id: `r${i}`,
      resource: d.resource,
      itemsPerMinute: d.itemsPerMinute,
    })),
    productTargets: [],
    miner: normalizeMinerSettings(opts?.miner),
    scoringMode: opts?.scoringMode === "weighted" ? "weighted" : "centered",
    scoringOptions: { ...DEFAULT_SCORING_OPTIONS, ...opts?.scoringOptions },
    seed: opts?.seed ?? null,
  });
}

/**
 * Map alternate recipe ClassNames → product overrides using each recipe’s
 * primary product (Docs first product line). For byproduct-selectable paths,
 * pass explicit {@link encodePlanHash} `recipeOverrides` instead.
 */
export function alternateRecipesToOverrides(
  alternateRecipes: readonly string[],
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rid of alternateRecipes) {
    const recipeId = rid.trim();
    if (!recipeId || recipeIndexById.get(recipeId) === undefined) continue;
    const primary = RECIPE_PRIMARY[recipeId];
    if (!primary || itemIndexById.get(primary) === undefined) continue;
    out[primary] = recipeId;
  }
  return out;
}

/**
 * Mode B stretch helper: target outputs + alternate recipe ClassNames → share hash.
 * Assumes default map/extractor settings unless overridden.
 * Does not reimplement a full factory graph — only sparse targets + recipe picks.
 */
export function encodeProductPlanHash(
  targets: ProductLinkTarget[],
  opts?: {
    alternateRecipes?: string[];
    externalItems?: string[];
    seed?: MapSeed;
    miner?: Partial<MinerSettings>;
    scoringMode?: ScoringMode;
    scoringOptions?: Partial<ScoringOptions>;
    /** Explicit product → recipe map (wins over alternateRecipes for the same product). */
    recipeOverrides?: Record<string, string>;
  },
): string {
  const fromAlts = alternateRecipesToOverrides(opts?.alternateRecipes ?? []);
  const recipeOverrides = { ...fromAlts, ...opts?.recipeOverrides };
  return encodePlanHash({
    mode: "product",
    rawDemand: [],
    productTargets: targets.map((t, i) => ({
      id: `p${i}`,
      productId: canonicalizeProductId(t.item),
      itemsPerMinute: t.itemsPerMinute,
    })),
    miner: normalizeMinerSettings(opts?.miner),
    scoringMode: opts?.scoringMode === "weighted" ? "weighted" : "centered",
    scoringOptions: { ...DEFAULT_SCORING_OPTIONS, ...opts?.scoringOptions },
    seed: opts?.seed ?? null,
    externalItems: opts?.externalItems,
    recipeOverrides,
  });
}
